# Generated by Django 4.2.11 on 2026-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('name_en', models.CharField(max_length=127, null=True)),
                ('name_uz', models.CharField(max_length=127, null=True)),
                ('name_ru', models.CharField(max_length=127, null=True)),
            ],
        ),
    ]
